"""Bilingual curated pathways. Snapshot notes are manually verified, not a live feed."""
import re
CAT_ELIG = 'https://cdn.digialm.com/per/g06/pub/32842/EForms/image/CAT2026/CAT_2026_Eligibility_26-07-26.pdf'
CATALOG = []
def add(id, category, title, aliases, en, hi, url):
    # Content order: overview, typical entry, stages, subjects, suggested preparation.
    CATALOG.append(dict(id=id, category=category, title=title, aliases=aliases.split('|'), en=en.split('~'), hi=hi.split('~'), url=url))

add('10','School','Class 10 / कक्षा 10','class 10|10th|कक्षा 10|दसवीं',
'Build school foundations and choose your next learning route.~Follow your board and school enrolment, attendance and assessment rules; these differ by board.~School/internal assessment and board examinations as applicable → Class 11, diploma or ITI options.~Mathematics, Science, Social Science and languages; use your actual board syllabus.~List chapters and diagnose weak ones → textbook exercises and written answers → weekly chapter tests → timed sample papers. Compare Science, Commerce, Humanities and vocational options by interests, prerequisites and costs.',
'स्कूल की बुनियाद मज़बूत करें और आगे का रास्ता चुनें।~अपने बोर्ड और स्कूल के नामांकन, उपस्थिति और मूल्यांकन नियम देखें; नियम बोर्ड के अनुसार बदलते हैं।~स्कूल/आंतरिक मूल्यांकन और लागू बोर्ड परीक्षा → कक्षा 11, डिप्लोमा या ITI विकल्प।~गणित, विज्ञान, सामाजिक विज्ञान और भाषाएँ; अपने बोर्ड का वास्तविक पाठ्यक्रम देखें।~अध्यायों और कमज़ोर हिस्सों की सूची → किताब के अभ्यास और लिखित उत्तर → साप्ताहिक टेस्ट → समयबद्ध नमूना प्रश्नपत्र। रुचि, ज़रूरी विषय और खर्च देखकर Science, Commerce, Humanities या व्यावसायिक विकल्प चुनें।', 'https://www.cbse.gov.in/')
add('12','School','Class 12 / कक्षा 12','class 12|12th|कक्षा 12|बारहवीं',
'Balance board performance with higher-education applications.~School/board conditions apply. College eligibility depends on course, required subjects and entrance rules.~Internal/practical assessment and board papers → relevant entrance/counselling or merit-based admission.~Your chosen stream subjects plus languages; prepare practical files and projects where required.~Finish concepts → practise board marking-scheme answers → revise with timed papers. Explore PCM: engineering/science; PCB: medicine/life sciences; Commerce: BCom/CA/management; Humanities: arts/law/social sciences. These are examples, not fixed career limits.',
'बोर्ड की तैयारी और उच्च शिक्षा के आवेदन साथ सँभालें।~स्कूल/बोर्ड के नियम लागू हैं। कॉलेज की पात्रता कोर्स, ज़रूरी विषय और प्रवेश नियमों पर निर्भर है।~आंतरिक/प्रैक्टिकल मूल्यांकन और बोर्ड पेपर → संबंधित प्रवेश परीक्षा/काउंसलिंग या मेरिट से प्रवेश।~अपने चुने हुए विषय और भाषाएँ; जहाँ आवश्यक हो प्रैक्टिकल फ़ाइल और प्रोजेक्ट तैयार करें।~सिद्धांत पूरे करें → अंक योजना के अनुसार उत्तर लिखें → समयबद्ध पेपर हल करें। PCM: engineering/science; PCB: medicine/life sciences; Commerce: BCom/CA/management; Humanities: arts/law/social sciences जैसे विकल्प देखें। ये उदाहरण हैं, करियर की सीमाएँ नहीं।', 'https://www.cbse.gov.in/')
add('neet','Entrance & professional','NEET UG','neet|नीट|mbbs',
'Entrance pathway for MBBS/BDS and other courses using NEET scores; qualifying does not guarantee a seat.~Typically 10+2 with Physics, Chemistry, Biology/Biotechnology and English; minimum age and category-specific marks apply. Verify the target-year bulletin and counselling rules.~Application → NEET UG → result → MCC/state or relevant counselling → document verification and admission.~Physics, Chemistry and Biology using the official target-year syllabus.~Map Class 11–12 chapters → study concepts and Biology NCERT closely → solve topic MCQs and numerical problems → keep an error notebook → take timed full mocks and revise. Budget for counselling and check college recognition.',
'MBBS/BDS और NEET स्कोर स्वीकार करने वाले अन्य कोर्स का प्रवेश मार्ग; केवल qualify करने से सीट पक्की नहीं होती।~आमतौर पर 10+2 में Physics, Chemistry, Biology/Biotechnology और English; न्यूनतम आयु और श्रेणी के अंक नियम लागू हैं। लक्ष्य वर्ष का bulletin और काउंसलिंग नियम जाँचें।~आवेदन → NEET UG → परिणाम → MCC/राज्य या संबंधित काउंसलिंग → दस्तावेज़ जाँच और प्रवेश।~आधिकारिक लक्ष्य-वर्ष पाठ्यक्रम के अनुसार Physics, Chemistry और Biology।~कक्षा 11–12 के अध्याय बाँटें → सिद्धांत और Biology NCERT पढ़ें → MCQ और numerical हल करें → गलतियों की कॉपी बनाएँ → समयबद्ध mock और दोहराई करें। कॉलेज की मान्यता और काउंसलिंग खर्च जाँचें।', 'https://neet.nta.nic.in/')
add('cat','Entrance & professional','CAT / MBA','cat|कैट|mba|एमबीए',
'Management entrance test used by IIMs and participating institutions; each institution has its own selection process.~CAT 2026: recognised bachelor’s degree with 50% or equivalent (45% for SC/ST/PwBD); eligible final-year candidates may apply provisionally. Specified professional qualifications are also accepted. See the linked eligibility PDF for full conditions.~CAT → institute-specific shortlist → interview/writing or other selection stages → admission offer.~Verbal Ability and Reading Comprehension, Data Interpretation and Logical Reasoning, Quantitative Ability.~Take a diagnostic → strengthen arithmetic/algebra and daily reading → practise DI/LR sets → sectional tests → full mocks with detailed analysis. Research programmes, fees and application requirements separately.',
'IIM और भाग लेने वाले संस्थानों के लिए management प्रवेश परीक्षा; हर संस्थान की चयन प्रक्रिया अलग है।~CAT 2026: मान्य स्नातक डिग्री में 50% या समकक्ष (SC/ST/PwBD के लिए 45%); पात्र अंतिम-वर्ष छात्र शर्तों के साथ आवेदन कर सकते हैं। निर्धारित professional qualifications भी स्वीकार हैं। पूरी शर्तें पात्रता PDF में देखें।~CAT → संस्थान की shortlist → interview/लेखन या अन्य चरण → प्रवेश प्रस्ताव।~Verbal Ability और Reading Comprehension, Data Interpretation और Logical Reasoning, Quantitative Ability।~प्रारंभिक टेस्ट → arithmetic/algebra और रोज़ पढ़ना → DI/LR sets → sectional tests → पूर्ण mocks और विश्लेषण। कोर्स, फीस और अलग आवेदन नियम भी देखें।', 'https://iimcat.ac.in/')
add('ca','Entrance & professional','CA / Chartered Accountant','ca|chartered accountant|सीए|चार्टर्ड अकाउंटेंट',
'ICAI professional qualification for accounting, audit, taxation and finance; not a government recruitment examination.~Foundation registration is available after Class 10; appearing in the exam requires the applicable Class 12 and study-period conditions. Eligible graduates/professionals may use Direct Entry to Intermediate; check ICAI rules.~Foundation route or eligible Direct Entry → Intermediate → prescribed training/courses and practical training → Final and other applicable requirements → membership.~Foundation: Accounting, Business Laws, Quantitative Aptitude, Business Economics. Later levels add tax, audit, reporting, costing and finance.~Confirm entry route and registration cut-off → follow ICAI study modules → practise accounting problems and law answers → revision/test papers and mock exams → plan training and exams around official eligibility milestones.',
'Accounting, audit, taxation और finance के लिए ICAI की professional qualification; यह सरकारी भर्ती परीक्षा नहीं है।~कक्षा 10 के बाद Foundation registration उपलब्ध है; परीक्षा देने के लिए लागू कक्षा 12 और अध्ययन अवधि की शर्तें पूरी करनी होती हैं। पात्र graduates/professionals Intermediate में Direct Entry ले सकते हैं; ICAI नियम देखें।~Foundation या पात्र Direct Entry → Intermediate → निर्धारित courses और practical training → Final तथा अन्य आवश्यकताएँ → membership।~Foundation: Accounting, Business Laws, Quantitative Aptitude, Business Economics। आगे tax, audit, reporting, costing और finance आते हैं।~प्रवेश मार्ग और registration cut-off जाँचें → ICAI modules पढ़ें → accounting और law उत्तरों का अभ्यास → revision papers और mocks → आधिकारिक पात्रता पड़ावों के अनुसार training और exams की योजना बनाएँ।', 'https://www.icai.org/post/exam')
add('upsc','Civil services','UPSC Civil Services','upsc|ias|ips|civil services|यूपीएससी|आईएएस',
'National civil-service recruitment, including IAS and IPS, subject to service allocation rules.~Typically a recognised degree; nationality, age, attempts and relaxations are notification-specific.~Prelims (screening) → written Mains → personality test → service allocation/medical requirements.~General Studies, CSAT, essay, optional subject and qualifying language papers as prescribed.~Read syllabus and previous papers → build history/polity/economy/geography basics → link current affairs → practise CSAT and answer writing → prelims mocks and Mains tests.',
'IAS और IPS सहित राष्ट्रीय सिविल सेवा भर्ती; सेवा आवंटन के अलग नियम हैं।~आमतौर पर मान्य स्नातक डिग्री; नागरिकता, आयु, प्रयास और छूट अधिसूचना के अनुसार।~Prelims → लिखित Mains → personality test → सेवा आवंटन/मेडिकल आवश्यकताएँ।~General Studies, CSAT, essay, optional subject और निर्धारित qualifying language papers।~पाठ्यक्रम और पुराने प्रश्न → इतिहास/राजव्यवस्था/अर्थव्यवस्था/भूगोल की बुनियाद → current affairs → CSAT और उत्तर लेखन → Prelims mocks और Mains tests।', 'https://upsc.gov.in/')
add('ssc','SSC','SSC CGL / CHSL / MTS / JE / Stenographer','ssc|cgl|chsl|mts|stenographer|एसएससी',
'Central recruitment family: CGL, CHSL, MTS/Havaldar, JE, Stenographer and Selection Posts.~Typical entry: CGL degree; CHSL Class 12; MTS Class 10; JE relevant engineering diploma/degree; Stenographer Class 12 plus skill. Some posts need extra subjects/experience.~Computer-based stages; typing/skill/trade or physical tests where prescribed → document/medical checks. Stages differ by exam.~Quantitative aptitude, reasoning, language and general awareness; JE adds engineering and Stenographer needs stenography.~Choose one notification/post → map its exact syllabus → practise maths/reasoning daily → build language and awareness → timed mocks; train typing/technical/physical skills where required.',
'केंद्रीय भर्ती समूह: CGL, CHSL, MTS/Havaldar, JE, Stenographer और Selection Posts।~सामान्य प्रवेश: CGL स्नातक; CHSL 12वीं; MTS 10वीं; JE संबंधित engineering diploma/degree; Stenographer 12वीं और skill। कुछ पदों में अतिरिक्त विषय/अनुभव ज़रूरी हैं।~Computer-based चरण; निर्धारित typing/skill/trade या physical test → दस्तावेज़/मेडिकल। चरण परीक्षा अनुसार बदलते हैं।~गणित, reasoning, भाषा और सामान्य जागरूकता; JE में engineering, Stenographer में stenography।~एक अधिसूचना/पद चुनें → उसका पाठ्यक्रम देखें → रोज़ गणित/reasoning → भाषा और जागरूकता → timed mocks; ज़रूरी typing/technical/physical skills का अभ्यास।', 'https://ssc.gov.in/')
add('bank','Banking & finance','Banking: IBPS / SBI / RBI','ibps|sbi|rbi|banking|bank po|बैंक|बैंकिंग',
'Public-sector banking and regulator pathways: IBPS PO/CSA/SO/RRB, SBI PO/Junior Associate and RBI recruitment. These are different employers and exams.~Many general posts require a degree; specialist posts need specified qualifications/experience. Age, local language and marks depend on the notice.~Prelims/Mains where prescribed; interview for relevant officer posts; language/other checks as notified. Not all roles have interviews.~Reasoning, quantitative aptitude, English, banking/current affairs; specialist or economics/finance content by role.~Choose employer and role → build calculation speed and reasoning accuracy → read financial news → timed sectionals → full mocks; prepare interviews only where required.',
'IBPS PO/CSA/SO/RRB, SBI PO/Junior Associate और RBI जैसे बैंक/नियामक मार्ग। नियोक्ता और परीक्षाएँ अलग हैं।~कई सामान्य पदों में स्नातक; specialist पदों में निर्धारित योग्यता/अनुभव। आयु, स्थानीय भाषा और अंक अधिसूचना अनुसार।~जहाँ लागू Prelims/Mains; संबंधित officer पदों के interview; अधिसूचित भाषा/अन्य जाँच। हर पद में interview नहीं होता।~Reasoning, गणित, English, banking/current affairs; पद के अनुसार specialist या economics/finance विषय।~नियोक्ता और पद चुनें → तेज़ गणना और सही reasoning → वित्तीय खबरें → timed sectionals → mocks; जहाँ आवश्यक हो interview तैयारी।', 'https://www.ibps.in/')
add('rail','Railways','Railways: RRB NTPC / Level 1 / ALP / JE','railway|railways|rrb ntpc|ntpc|alp|रेलवे',
'Railway Recruitment Board/Centralised Employment Notice pathways for non-technical and technical posts. Railway RRB is not IBPS Regional Rural Banks.~NTPC has undergraduate (Class 12) and graduate posts. Level 1, ALP and JE have notice-specific school/ITI/diploma/degree conditions; technical trades and medical standards matter.~CBT stages → aptitude/typing/physical tests where applicable → document verification and medical examination.~Maths, reasoning, general awareness/science; technical subjects for applicable posts.~Identify CEN number and exact post → verify trade and medical eligibility → cover syllabus → CBT mocks → prescribed skill/aptitude/fitness preparation.',
'रेलवे में non-technical और technical पदों के RRB/CEN मार्ग। रेलवे RRB, IBPS Regional Rural Banks से अलग है।~NTPC में 12वीं और graduate पद हैं। Level 1, ALP और JE की school/ITI/diploma/degree शर्तें अधिसूचना अनुसार; trade और medical standards महत्वपूर्ण हैं।~CBT चरण → लागू aptitude/typing/physical test → दस्तावेज़ और मेडिकल।~गणित, reasoning, general awareness/science; लागू पदों में technical विषय।~CEN नंबर और सही पद चुनें → trade/medical पात्रता जाँचें → पाठ्यक्रम → CBT mocks → निर्धारित skill/aptitude/fitness तैयारी।', 'https://www.rrbcdg.gov.in/')
add('nda','Defence & police','NDA / NA','nda|national defence academy|एनडीए',
'Officer-training entry after school for eligible defence wings.~Class 12 route; Air Force/Naval wings require specified science subjects. Exact date-of-birth window, marital status, nationality and medical conditions are mandatory.~Written examination → SSB → medical examination → merit and training.~Mathematics and General Ability Test; communication, teamwork and physical readiness.~Strengthen school maths/science and English → current affairs and previous papers → timed tests → practise communication/teamwork and gradual safe fitness.',
'पात्र defence wings में स्कूल के बाद officer training का मार्ग।~12वीं का मार्ग; Air Force/Naval wings में निर्धारित science subjects ज़रूरी। जन्मतिथि सीमा, वैवाहिक स्थिति, नागरिकता और मेडिकल शर्तें अनिवार्य हैं।~लिखित परीक्षा → SSB → मेडिकल → मेरिट और training।~Mathematics और General Ability Test; संवाद, teamwork और शारीरिक तैयारी।~स्कूल गणित/science और English → current affairs/पुराने प्रश्न → timed tests → संवाद/teamwork और धीरे-धीरे सुरक्षित fitness अभ्यास।', 'https://upsc.gov.in/')
add('cds','Defence & police','CDS / AFCAT','cds|afcat|सीडीएस|एफकैट',
'Graduate officer-entry pathways; CDS and AFCAT have separate authorities and branch rules.~Relevant degree and branch-specific school subjects/engineering conditions; exact age window, marital status and medical standards must be checked.~Written test → SSB/AFSB → medical → merit/training, with branch-specific additional tests.~CDS: English, general knowledge and maths where applicable. AFCAT: English, awareness, numerical and reasoning/military aptitude as notified.~Select academy/branch → verify qualification → practise prescribed written sections → timed papers → structured interview, teamwork and fitness preparation.',
'Graduates के लिए officer-entry मार्ग; CDS और AFCAT के प्राधिकरण और branch नियम अलग हैं।~संबंधित degree और branch के school subjects/engineering नियम; आयु सीमा, वैवाहिक स्थिति और medical standards जाँचें।~लिखित परीक्षा → SSB/AFSB → मेडिकल → मेरिट/training; branch के अतिरिक्त tests लागू हो सकते हैं।~CDS: English, general knowledge और जहाँ लागू maths। AFCAT: अधिसूचित English, awareness, numerical और reasoning/military aptitude।~Academy/branch चुनें → योग्यता जाँचें → लिखित sections → timed papers → interview, teamwork और fitness तैयारी।', 'https://upsc.gov.in/')
add('police','Defence & police','Police / SSC GD / CAPF AC / Agniveer','police|ssc gd|capf|agniveer|पुलिस|अग्निवीर',
'Uniformed-service categories, not one exam. CAPF AC is an officer route; constable and Agniveer routes have different service conditions.~CAPF AC generally requires a degree; constable/Agniveer education varies by post/trade. Check DOB, physical/medical standards, domicile, gender-specific rules and service terms.~Written/online test and prescribed physical, medical, document or interview stages; order varies by recruitment.~Reasoning, language, general awareness and maths/science; CAPF adds written general studies/essay components.~Choose a force and exact notice → confirm education/physical rules → study written syllabus → timed tests → progressive safe fitness; understand Agniveer engagement and retention terms before applying.',
'वर्दीधारी सेवा श्रेणियाँ, एक परीक्षा नहीं। CAPF AC officer मार्ग है; constable और Agniveer की सेवा शर्तें अलग हैं।~CAPF AC में सामान्यतः स्नातक; constable/Agniveer में पद/trade अनुसार शिक्षा। जन्मतिथि, physical/medical, domicile, gender-specific नियम और सेवा शर्तें जाँचें।~लिखित/online और निर्धारित physical, medical, document या interview चरण; क्रम भर्ती अनुसार।~Reasoning, भाषा, awareness और maths/science; CAPF में general studies/essay लेखन भी।~बल और अधिसूचना चुनें → शिक्षा/physical नियम → लिखित पाठ्यक्रम → timed tests → सुरक्षित क्रमिक fitness; आवेदन से पहले Agniveer की नियुक्ति और retention शर्तें समझें।', 'https://ssc.gov.in/')
add('teach','Teaching','CTET / State TET / KVS / NVS','ctet|tet|kvs|nvs|teacher|teaching|शिक्षक|सीटेट',
'Teacher eligibility and recruitment are separate: CTET/TET qualification alone is not a job offer.~Prescribed teacher-education and academic qualifications depend on class level and current NCTE/recruitment rules; do not assume any degree or BEd qualifies for every level.~Eligible training/degree → applicable TET → separate recruitment selection → verification.~Child development/pedagogy, languages and level-specific mathematics, environment, science or social studies; subject expertise for recruitment.~Choose primary/upper-primary/secondary role → verify exact qualification → study pedagogy and subject content → previous papers and mocks → prepare recruitment-specific sections.',
'Teacher eligibility और भर्ती अलग हैं: CTET/TET पास करना नौकरी का प्रस्ताव नहीं।~Teacher-education और academic योग्यता कक्षा स्तर तथा वर्तमान NCTE/भर्ती नियमों पर निर्भर है; हर degree या BEd हर स्तर के लिए पात्र नहीं।~पात्र training/degree → लागू TET → अलग भर्ती चयन → सत्यापन।~बाल विकास/pedagogy, भाषाएँ और स्तर अनुसार गणित, पर्यावरण, विज्ञान या सामाजिक अध्ययन; भर्ती में विषय विशेषज्ञता।~Primary/upper-primary/secondary पद चुनें → सही योग्यता जाँचें → pedagogy और विषय पढ़ें → पुराने प्रश्न/mocks → भर्ती-विशेष sections तैयार करें।', 'https://ctet.nic.in/')
add('state','State services','State PSC / Subordinate services','state psc|state pcs|uppsc|bpsc|mppsc|uppsssc|राज्य पीसीएस',
'State civil services and subordinate recruitment, such as UPPSC, BPSC, MPPSC and state selection commissions.~Degree/school/technical requirements vary by post; check age, language, domicile/reservation and state-specific certificates.~Prelims/Mains/interview for many civil-service posts; other posts may use screening, skill or physical tests.~State history/geography/economy, general studies, current affairs, aptitude and prescribed languages.~Select state and post → read its syllabus and past papers → national plus state-specific study → answer writing/skill practice → mocks and document checklist.',
'UPPSC, BPSC, MPPSC और राज्य चयन आयोगों जैसी civil service और subordinate भर्तियाँ।~पद अनुसार degree/school/technical योग्यता; आयु, भाषा, domicile/reservation और राज्य प्रमाणपत्र जाँचें।~कई civil-service पदों में Prelims/Mains/interview; अन्य में screening, skill या physical tests।~राज्य इतिहास/भूगोल/अर्थव्यवस्था, general studies, current affairs, aptitude और निर्धारित भाषाएँ।~राज्य और पद चुनें → पाठ्यक्रम/पुराने प्रश्न → राष्ट्रीय और राज्य-विशेष अध्ययन → उत्तर लेखन/skill → mocks और दस्तावेज़ सूची।', 'https://uppsc.up.nic.in/')
add('technical','Technical & specialist','Engineering / PSU / ESE / GATE','gate|ese|psu|engineering services|गेट',
'Technical recruitment and higher-study pathways. GATE is an examination used by participating institutions/employers, not a guaranteed PSU job.~Relevant discipline and qualification required by the admitting institution/employer. GATE eligibility and employer eligibility are separate.~GATE score and employer selection where used; ESE has its own UPSC stages; other employers run separate tests/interviews.~Core engineering discipline, mathematics/aptitude and any employer-specific general studies.~Select discipline and employer → verify accepted qualification/paper → core concepts and numerical practice → previous papers and mocks → interview/project preparation.',
'Technical भर्ती और उच्च शिक्षा के मार्ग। GATE स्वीकार करने वाले संस्थान/नियोक्ता अलग हैं; GATE से PSU नौकरी पक्की नहीं।~संस्थान/नियोक्ता की संबंधित discipline और योग्यता ज़रूरी। GATE और employer पात्रता अलग हैं।~जहाँ उपयोग हो GATE स्कोर और employer चयन; ESE के अपने UPSC चरण; अन्य नियोक्ता अलग tests/interviews लेते हैं।~Core engineering, maths/aptitude और employer-specific general studies।~Discipline और employer चुनें → स्वीकार्य qualification/paper → concepts और numerical → पुराने papers/mocks → interview/project तैयारी।', 'https://upsc.gov.in/')
add('net','Teaching','UGC NET / CSIR NET','ugc net|csir net|नेट',
'Eligibility/fellowship and higher-study pathways depending on result category and applicable rules, not automatic faculty appointment.~Relevant postgraduate or permitted undergraduate route with prescribed marks; subject, JRF age and appointment eligibility differ. Check the target-cycle bulletin.~Application → test → result category → separate university/fellowship/admission or recruitment process.~UGC NET: teaching/research aptitude and selected subject. CSIR NET: aptitude and selected science discipline.~Check subject and qualification → read syllabus → strengthen research aptitude/core subject → solve past papers → full mocks and error review.',
'परिणाम श्रेणी और लागू नियमों के अनुसार eligibility/fellowship और उच्च शिक्षा मार्ग; faculty नियुक्ति अपने-आप नहीं होती।~संबंधित postgraduate या अनुमत undergraduate मार्ग में निर्धारित अंक; विषय, JRF आयु और नियुक्ति पात्रता अलग हैं। लक्ष्य-cycle bulletin देखें।~आवेदन → test → परिणाम श्रेणी → अलग university/fellowship/admission या भर्ती प्रक्रिया।~UGC NET: teaching/research aptitude और चुना विषय। CSIR NET: aptitude और चुनी science discipline।~विषय/योग्यता जाँचें → पाठ्यक्रम → research aptitude/core subject → पुराने papers → mocks और गलतियों की दोहराई।', 'https://ugcnet.nta.ac.in/')

# Every note describes only what was actually visible in the cited source.
NOTES = {
 'cat': ('Verified official dates + eligibility', 'आधिकारिक तारीखें और पात्रता सत्यापित',
  'CAT 2026 registration closes 22 September 2026 at 5:00 PM IST; admit-card download starts 4 November; test day is 29 November. The official eligibility PDF confirms the degree percentages and provisional final-year route described above.',
  'CAT 2026 registration 22 सितंबर 2026 शाम 5 बजे IST बंद; admit-card download 4 नवंबर से; परीक्षा 29 नवंबर। आधिकारिक पात्रता PDF ऊपर दिए degree प्रतिशत और अंतिम-वर्ष के सशर्त मार्ग की पुष्टि करती है।', [('CAT official portal','https://iimcat.ac.in/'),('CAT 2026 eligibility',CAT_ELIG)]),
 'neet': ('Verified syllabus notice only', 'केवल पाठ्यक्रम सूचना सत्यापित',
  'The NMC notice dated 22 December 2025 provides the updated NEET UG 2026 syllabus. This is not verification of an active application window, final result or 2027 schedule. Current detailed eligibility has not been independently checked here.',
  '22 दिसंबर 2025 का NMC notice NEET UG 2026 का updated syllabus देता है। इससे चालू आवेदन, अंतिम परिणाम या 2027 की तारीखें सत्यापित नहीं होतीं। वर्तमान विस्तृत पात्रता यहाँ अलग से जाँची नहीं गई है।', [('1','https://nta.ac.in/Download/Notice/Notice_20260108180635.pdf')]),
 'ca': ('Verified official exam index only', 'केवल आधिकारिक परीक्षा सूची सत्यापित',
  'ICAI’s examination page links an “Examinations — September & November 2026” page. Dates, amendments and personal exam eligibility must be checked in its underlying notices; this card does not assert an open application window.',
  'ICAI की परीक्षा सूची में “Examinations — September & November 2026” पेज है। तारीखें, संशोधन और अपनी परीक्षा पात्रता उसकी अधिसूचनाओं में देखें; यहाँ आवेदन खुले होने का दावा नहीं है।', [('ICAI examination index','https://www.icai.org/post/exam'),('Session notices','https://www.icai.org/post/exam-sep-nov-2026')]),
 'ssc': ('Verified notice-board entries only', 'केवल notice-board प्रविष्टियाँ सत्यापित',
  'The official board lists a Sub-Inspector in Delhi Police/CAPF Examination 2026 notice dated 10 September and an important JE Examination 2026 notice dated 17 September. Full deadlines and eligibility were not extracted; read the actual PDFs before applying.',
  'आधिकारिक बोर्ड पर Delhi Police/CAPF Sub-Inspector 2026 की 10 सितंबर सूचना और JE 2026 की 17 सितंबर महत्वपूर्ण सूचना है। पूरी deadlines और पात्रता नहीं निकाली गई हैं; आवेदन से पहले मूल PDF पढ़ें।', [('SSC notice board','https://ssc.gov.in/')]),
 'bank': ('Verified IBPS update entries only', 'केवल IBPS update प्रविष्टियाँ सत्यापित',
  'IBPS lists a CRP-RRBs-XV corrigendum and updated vacancies dated 15 September 2026. These refer to Regional Rural Banks, not Railway RRB. No vacancy count, deadline or personal eligibility is asserted here.',
  'IBPS पर 15 सितंबर 2026 का CRP-RRBs-XV corrigendum और updated vacancies सूचीबद्ध हैं। ये Regional Rural Banks हैं, रेलवे RRB नहीं। यहाँ vacancy संख्या, deadline या व्यक्तिगत पात्रता का दावा नहीं है।', [('IBPS official updates','https://www.ibps.in/'),('Corrigendum','https://www.ibps.in/wp-content/uploads/Corrigendum-CRP-RRBs-XV-1.pdf')]),
}
SCHOOL_NOTE = ('Verified CBSE notice entry only','केवल CBSE सूचना प्रविष्टि सत्यापित',
 'CBSE lists “Prior Intimation of Submission of List of Candidates (LOC) for Class X/XII Examination-2026-27”, dated 10 September 2026. Ask your school about its process. This does not apply to every state board or establish board exam dates.',
 'CBSE पर 10 सितंबर 2026 की कक्षा X/XII परीक्षा 2026–27 के LOC की पूर्व सूचना है। प्रक्रिया अपने स्कूल से पूछें। यह हर राज्य बोर्ड पर लागू नहीं और बोर्ड परीक्षा तारीख की पुष्टि नहीं है।',
 [('CBSE official board','https://www.cbse.gov.in/cbsenew/cbse.html'),('LOC notice','https://www.cbse.gov.in/cbsenew/documents/LOC_Prior_Information_10092026.pdf')])
NOTES['10'] = NOTES['12'] = SCHOOL_NOTE

def find_path(question):
    q = question.casefold()
    matches = [(len(alias), entry) for entry in CATALOG for alias in entry['aliases']
               if re.search(r'(?<!\w)' + re.escape(alias) + r'(?!\w)', q)]
    return max(matches, key=lambda pair: pair[0])[1] if matches else None


def render_path(entry, language='en'):
    hi = language == 'hi'
    headings = ['परिचय','सामान्य प्रवेश / पात्रता','चरण','मुख्य विषय','सुझाया तैयारी रोडमैप'] if hi else ['Overview','Typical entry / eligibility','Stages','Core subjects','Suggested preparation roadmap']
    lines = [f"## {entry['title']}"]
    for heading, body in zip(headings, entry[language]):
        lines.append(f'### {heading}\n{body}')
    lines.append(('तैयारी के चरण सुझाव हैं, चयन या समय-सीमा की गारंटी नहीं। आयु, श्रेणी-छूट, प्रयास, विषय, फीस, मेडिकल और अंतिम तारीख के लिए सही वर्ष/पद की आधिकारिक सूचना मान्य है।' if hi else 'Preparation stages are suggestions, not selection or timeline guarantees. The exact year/post notification governs age, category relaxations, attempts, subjects, fees, medical standards and deadlines.'))
    lines.append(f"[{('आधिकारिक पोर्टल' if hi else 'Official portal')}]({entry['url']})")
    note = NOTES.get(entry['id'])
    lines.append('### ' + ('वर्तमान सूचना • 17 सितंबर 2026 को जाँच' if hi else 'Current information • checked 17 September 2026'))
    if note:
        lines.append(f'**{note[1] if hi else note[0]}**\n\n{note[3] if hi else note[2]}')
        lines.extend(f'[{label}]({url})' for label, url in note[4])
    else:
        lines.append('इस मार्ग की वर्तमान अधिसूचना/पात्रता सत्यापित नहीं है। सामान्य मार्गदर्शन ही है; आधिकारिक पोर्टल पर लक्ष्य भर्ती की सूचना देखें।' if hi else 'Current notification and detailed eligibility not verified for this pathway. General guidance only; check the target recruitment notice on the official portal.')
    lines.append('यह सेव किया गया snapshot है, live feed नहीं। बाद के संशोधन आधिकारिक साइट पर देखें।' if hi else 'This is a saved snapshot, not a live feed. Check the official site for subsequent amendments.')
    return '\n\n'.join(lines)
